name: Atcoder

on:
  schedule:
    - cron: "0 4 * * *"

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: ganyariya/atcoder-readme-action@master
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          USERNAME: "ganyariya"
          ATCODER_ACCOUNT: "ganyariya"
